---
- name: "Creating Aws Infra Using Ansible"
  hosts: localhost
  become: true
  vars:
    access_key: " your access-key "
    secret_key: " your secret-key "
    region: "ap-south-1"
  tasks:

    - name: Basic deploy of a service
      community.general.terraform:
        project_path: 'myproject/'
        state: present
        force_init: true

    - name: "Amazon - Fetching Ec2 Info"
      ec2_instance_info :
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ secret_key }}"
        region: "{{ region }}"
        filters:
            "tag:aws:autoscaling:groupName" : "new"
      register: ec2

    - name: "Amazon - Creating Dynamic Inventory"
      add_host:
        hostname: '{{ item.public_ip_address }}'
        ansible_host: '{{ item.public_ip_address }}'
        ansible_port: 22
        groups:
          - backends
        ansible_ssh_private_key_file: "./terrakey"
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
      with_items: "{{ ec2.instances }}"


- name: "Deployment From GitHub"
  hosts: backends
  become: true
  serial: 1
  vars:
    packages:
      - git
    repo: https://github.com/devasivaram/aws-elb-site.git
  tasks:

    - name: "Package Installation"
      yum:
        name: "{{ packages }}"
        state: present

    - name: "Clonning Github Repository {{ repo }}"
      git:
        repo: "{{ repo }}"
        dest: "/var/website/"
      register: gitstatus

    - name: "Backend off loading from elb"
      when: gitstatus.changed
      file:
        path: "/var/www/html/health.html"
        mode: 0000

    - name: "waiting for connection draining"
      when: gitstatus.changed
      wait_for:
        timeout: 30

    - name: "updating site contents"
      when: gitstatus.changed
      copy:
        src: "/var/website/"
        dest: "/var/www/html/"
        remote_src: true
        owner: apache
        group: apache

    - name: "loading backend to elb"
      when: gitstatus.changed
      file:
        path: "/var/www/html/health.html"
        mode: 0644

    - name: "waiting for connection draining"
      when: gitstatus.changed
      wait_for:
        timeout: 20